version: '3'

services:
  scraper:
    build: .
    volumes:
        ./scrapy_redis_demo:/usr/src/app
    depends_on:
      - redis
    restart: always
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
