version: '3'

services:
  scraper:
    build: .
    volumes:
      - ./scrapy_redis_demo:/usr/src/app
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
